# Generated by Django 4.2.2 on 2023-06-25 14:11

from django.db import migrations

def update_passwords(apps, schema_editor):
    User = apps.get_model('flight', 'User')
    for user in User.objects.all():
        user.password = make_password(user.password)
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
    ]
